using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Auto_Wash.Data;

namespace Auto_Wash.Controllers
{
    /// <summary>
    /// Demo-only tools: browse and edit raw database tables from the admin UI
    /// so demo scenarios (booking times, statuses...) can be tweaked without
    /// opening Supabase directly.
    /// </summary>
    public class DemoToolsController : Controller
    {
        private readonly AutoWashDbContext _context;

        public DemoToolsController(AutoWashDbContext context)
        {
            _context = context;
        }

        private bool IsAdminOrStaff()
        {
            var role = HttpContext.Session.GetString("UserRole");
            return string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase) ||
                   string.Equals(role, "staff", StringComparison.OrdinalIgnoreCase);
        }

        [HttpGet]
        [Route("api/admin/demo-tools/tables")]
        public IActionResult GetTables()
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            try
            {
                var tables = _context.Model.GetEntityTypes()
                    .Where(et => et.GetTableName() != null)
                    .Select(et => new
                    {
                        name = et.GetTableName(),
                        columns = GetColumnInfo(et).Select(c => new
                        {
                            name = c.Name,
                            storeType = c.StoreType,
                            clrType = c.ClrType.Name,
                            isPrimaryKey = c.IsPrimaryKey,
                            isNullable = c.IsNullable,
                            isAutoGenerated = c.IsAutoGenerated,
                            enumLabels = c.EnumLabels
                        })
                    })
                    .OrderBy(t => t.name)
                    .ToList();

                return Ok(new { success = true, tables });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpGet]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> GetRows(string table, int page = 1, int pageSize = 20, string? search = null, string? sortBy = null, string? sortDir = null)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });

            if (page < 1) page = 1;
            if (pageSize < 1 || pageSize > 200) pageSize = 20;

            try
            {
                var tableName = entityType.GetTableName()!;
                var columns = GetColumnInfo(entityType);
                var pkColumns = columns.Where(c => c.IsPrimaryKey).Select(c => c.Name).ToList();
                // Sort column must exist in the EF model — rejects arbitrary identifiers
                var orderBy = pkColumns.Count > 0
                    ? string.Join(", ", pkColumns.Select(Quote))
                    : Quote(columns[0].Name);
                if (!string.IsNullOrWhiteSpace(sortBy))
                {
                    var sortColumn = columns.FirstOrDefault(c => string.Equals(c.Name, sortBy, StringComparison.OrdinalIgnoreCase));
                    if (sortColumn == null)
                    {
                        return BadRequest(new { success = false, message = $"Cột sort '{sortBy}' không tồn tại trong bảng '{table}'." });
                    }
                    var direction = string.Equals(sortDir, "desc", StringComparison.OrdinalIgnoreCase) ? "DESC" : "ASC";
                    orderBy = $"{Quote(sortColumn.Name)} {direction}";
                }

                // Search: match the term against every column, cast to text so it works for numbers/dates too
                var whereClause = "";
                if (!string.IsNullOrWhiteSpace(search))
                {
                    var likeConditions = columns.Select(c => $"{Quote(c.Name)}::text ILIKE @search");
                    whereClause = $" WHERE ({string.Join(" OR ", likeConditions)})";
                }

                var result = await WithConnectionAsync(async conn =>
                {
                    long totalCount;
                    using (var countCmd = conn.CreateCommand())
                    {
                        countCmd.CommandText = $"SELECT COUNT(*) FROM {Quote(tableName)}{whereClause}";
                        AddSearchParameter(countCmd, whereClause, search);
                        totalCount = Convert.ToInt64(await countCmd.ExecuteScalarAsync());
                    }

                    var rows = new List<Dictionary<string, object?>>();
                    using (var cmd = conn.CreateCommand())
                    {
                        cmd.CommandText =
                            $"SELECT * FROM {Quote(tableName)}{whereClause} ORDER BY {orderBy} " +
                            $"LIMIT {pageSize} OFFSET {(page - 1) * pageSize}";
                        AddSearchParameter(cmd, whereClause, search);
                        using var reader = await cmd.ExecuteReaderAsync();
                        while (await reader.ReadAsync())
                        {
                            var row = new Dictionary<string, object?>();
                            for (int i = 0; i < reader.FieldCount; i++)
                            {
                                row[reader.GetName(i)] = ReadValue(reader.GetValue(i));
                            }
                            rows.Add(row);
                        }
                    }

                    return new { totalCount, rows };
                });

                return Ok(new { success = true, page, pageSize, totalCount = result.totalCount, rows = result.rows });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        public class RowRequest
        {
            public Dictionary<string, JsonElement>? Pk { get; set; }
            public Dictionary<string, JsonElement>? Values { get; set; }
        }

        [HttpPut]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> UpdateRow(string table, [FromBody] RowRequest request)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });
            if (request?.Pk == null || request.Pk.Count == 0) return BadRequest(new { success = false, message = "Thiếu khóa chính (pk)." });
            if (request.Values == null || request.Values.Count == 0) return BadRequest(new { success = false, message = "Không có cột nào để cập nhật." });

            var columns = GetColumnInfo(entityType);

            try
            {
                var affected = await WithConnectionAsync(async conn =>
                {
                    using var cmd = conn.CreateCommand();
                    var setParts = new List<string>();
                    int i = 0;
                    foreach (var (colName, jsonValue) in request.Values)
                    {
                        var col = FindColumnOrThrow(columns, colName, table);
                        setParts.Add($"{Quote(col.Name)} = {AddTypedParameter(cmd, $"v{i++}", jsonValue, col)}");
                    }

                    var whereClause = BuildPkWhere(cmd, columns, request.Pk, table);
                    cmd.CommandText = $"UPDATE {Quote(entityType.GetTableName()!)} SET {string.Join(", ", setParts)} WHERE {whereClause}";
                    return await cmd.ExecuteNonQueryAsync();
                });

                if (affected == 0) return NotFound(new { success = false, message = "Không tìm thấy row với khóa chính này." });
                return Ok(new { success = true, message = $"Đã cập nhật {affected} row.", affected });
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpPost]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> InsertRow(string table, [FromBody] RowRequest request)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });
            if (request?.Values == null || request.Values.Count == 0) return BadRequest(new { success = false, message = "Không có dữ liệu để thêm." });

            var columns = GetColumnInfo(entityType);

            try
            {
                var createdRow = await WithConnectionAsync(async conn =>
                {
                    using var cmd = conn.CreateCommand();
                    var colNames = new List<string>();
                    var placeholders = new List<string>();
                    int i = 0;
                    foreach (var (colName, jsonValue) in request.Values)
                    {
                        var col = FindColumnOrThrow(columns, colName, table);
                        if (col.IsAutoGenerated) continue; // identity PK — let the DB generate it
                        colNames.Add(Quote(col.Name));
                        placeholders.Add(AddTypedParameter(cmd, $"v{i++}", jsonValue, col));
                    }
                    if (colNames.Count == 0) throw new ArgumentException("Không có cột hợp lệ nào để thêm.");

                    cmd.CommandText =
                        $"INSERT INTO {Quote(entityType.GetTableName()!)} ({string.Join(", ", colNames)}) " +
                        $"VALUES ({string.Join(", ", placeholders)}) RETURNING *";

                    using var reader = await cmd.ExecuteReaderAsync();
                    if (!await reader.ReadAsync()) return null;
                    var row = new Dictionary<string, object?>();
                    for (int f = 0; f < reader.FieldCount; f++)
                    {
                        row[reader.GetName(f)] = ReadValue(reader.GetValue(f));
                    }
                    return row;
                });

                return Ok(new { success = true, message = "Đã thêm row mới.", row = createdRow });
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        private static ColumnInfo FindColumnOrThrow(List<ColumnInfo> columns, string name, string table)
        {
            return columns.FirstOrDefault(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase))
                ?? throw new ArgumentException($"Cột '{name}' không tồn tại trong bảng '{table}'.");
        }

        /// <summary>
        /// Adds a parameter carrying the JSON value as text and returns the SQL placeholder
        /// with a cast to the column's store type — values never get concatenated into SQL.
        /// </summary>
        private static string AddTypedParameter(DbCommand cmd, string name, JsonElement jsonValue, ColumnInfo col)
        {
            var p = cmd.CreateParameter();
            p.ParameterName = name;
            if (jsonValue.ValueKind == JsonValueKind.Null ||
                (jsonValue.ValueKind == JsonValueKind.String && jsonValue.GetString() == "" && col.IsNullable && col.ClrType != typeof(string)))
            {
                p.Value = DBNull.Value;
                cmd.Parameters.Add(p);
                return $"@{name}";
            }
            p.Value = jsonValue.ValueKind == JsonValueKind.String ? jsonValue.GetString()! : jsonValue.GetRawText();
            cmd.Parameters.Add(p);
            return $"@{name}::{col.StoreType}";
        }

        private static string BuildPkWhere(DbCommand cmd, List<ColumnInfo> columns, Dictionary<string, JsonElement> pk, string table)
        {
            var pkColumns = columns.Where(c => c.IsPrimaryKey).ToList();
            if (pkColumns.Count == 0) throw new ArgumentException($"Bảng '{table}' không có khóa chính — không hỗ trợ sửa/xóa.");

            var parts = new List<string>();
            int i = 0;
            foreach (var pkCol in pkColumns)
            {
                if (!pk.TryGetValue(pkCol.Name, out var value) &&
                    !pk.TryGetValue(pkCol.Name.ToLowerInvariant(), out value))
                {
                    throw new ArgumentException($"Thiếu giá trị khóa chính '{pkCol.Name}'.");
                }
                parts.Add($"{Quote(pkCol.Name)} = {AddTypedParameter(cmd, $"k{i++}", value, pkCol)}");
            }
            return string.Join(" AND ", parts);
        }

        private sealed class ColumnInfo
        {
            public string Name { get; init; } = string.Empty;
            public string StoreType { get; init; } = string.Empty;
            public Type ClrType { get; init; } = typeof(object);
            public bool IsPrimaryKey { get; init; }
            public bool IsNullable { get; init; }
            public bool IsAutoGenerated { get; init; }
            public Dictionary<int, string>? EnumLabels { get; init; }
        }

        private IEntityType? FindEntityType(string tableName)
        {
            return _context.Model.GetEntityTypes()
                .FirstOrDefault(et => string.Equals(et.GetTableName(), tableName, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>Quotes a Postgres identifier; the only untrusted part of built SQL — values always go through parameters.</summary>
        private static string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

        private async Task<T> WithConnectionAsync<T>(Func<DbConnection, Task<T>> action)
        {
            var conn = _context.Database.GetDbConnection();
            bool wasOpen = conn.State == System.Data.ConnectionState.Open;
            if (!wasOpen) await conn.OpenAsync();
            try
            {
                return await action(conn);
            }
            finally
            {
                if (!wasOpen) await conn.CloseAsync();
            }
        }

        private static void AddSearchParameter(DbCommand cmd, string whereClause, string? search)
        {
            if (string.IsNullOrEmpty(whereClause)) return;
            var p = cmd.CreateParameter();
            p.ParameterName = "search";
            p.Value = $"%{search}%";
            cmd.Parameters.Add(p);
        }

        /// <summary>Converts a raw DB value to a JSON-friendly shape; matches datetime-local format on the frontend.</summary>
        private static object? ReadValue(object? value)
        {
            if (value == null || value is DBNull) return null;
            if (value is DateTime dt) return dt.ToString("yyyy-MM-ddTHH:mm:ss");
            if (value is byte[] bytes) return $"[bytea {bytes.Length} bytes]";
            return value;
        }

        private static List<ColumnInfo> GetColumnInfo(IEntityType entityType)
        {
            var tableName = entityType.GetTableName()!;
            var storeObject = Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Table(tableName, entityType.GetSchema());
            var pkProps = entityType.FindPrimaryKey()?.Properties ?? (IReadOnlyList<IProperty>)Array.Empty<IProperty>();

            var columns = new List<ColumnInfo>();
            foreach (var prop in entityType.GetProperties())
            {
                var columnName = prop.GetColumnName(storeObject);
                if (columnName == null) continue;

                var clrType = Nullable.GetUnderlyingType(prop.ClrType) ?? prop.ClrType;
                Dictionary<int, string>? enumLabels = null;
                if (clrType.IsEnum)
                {
                    enumLabels = Enum.GetValues(clrType).Cast<object>()
                        .ToDictionary(v => Convert.ToInt32(v), v => v.ToString()!);
                }

                columns.Add(new ColumnInfo
                {
                    Name = columnName,
                    StoreType = prop.GetColumnType(),
                    ClrType = clrType,
                    IsPrimaryKey = pkProps.Contains(prop),
                    IsNullable = prop.IsNullable,
                    IsAutoGenerated = prop.ValueGenerated == ValueGenerated.OnAdd && pkProps.Contains(prop),
                    EnumLabels = enumLabels
                });
            }
            return columns;
        }
    }
}
