using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Auto_Wash.Data;

namespace Auto_Wash.Controllers
{
    /// <summary>
    /// Demo-only tools: browse and edit raw database tables from the admin UI
    /// so demo scenarios (booking times, statuses...) can be tweaked without
    /// opening Supabase directly.
    /// </summary>
    public class DemoToolsController : Controller
    {
        private readonly AutoWashDbContext _context;

        public DemoToolsController(AutoWashDbContext context)
        {
            _context = context;
        }

        private bool IsAdminOrStaff()
        {
            var role = HttpContext.Session.GetString("UserRole");
            return string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase) ||
                   string.Equals(role, "staff", StringComparison.OrdinalIgnoreCase);
        }

        [HttpGet]
        [Route("api/admin/demo-tools/tables")]
        public IActionResult GetTables()
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            try
            {
                var tables = _context.Model.GetEntityTypes()
                    .Where(et => et.GetTableName() != null)
                    .Select(et => new
                    {
                        name = et.GetTableName(),
                        columns = GetColumnInfo(et).Select(c => new
                        {
                            name = c.Name,
                            storeType = c.StoreType,
                            clrType = c.ClrType.Name,
                            isPrimaryKey = c.IsPrimaryKey,
                            isNullable = c.IsNullable,
                            isAutoGenerated = c.IsAutoGenerated,
                            enumLabels = c.EnumLabels
                        })
                    })
                    .OrderBy(t => t.name)
                    .ToList();

                return Ok(new { success = true, tables });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        private sealed class ColumnInfo
        {
            public string Name { get; init; } = string.Empty;
            public string StoreType { get; init; } = string.Empty;
            public Type ClrType { get; init; } = typeof(object);
            public bool IsPrimaryKey { get; init; }
            public bool IsNullable { get; init; }
            public bool IsAutoGenerated { get; init; }
            public Dictionary<int, string>? EnumLabels { get; init; }
        }

        private IEntityType? FindEntityType(string tableName)
        {
            return _context.Model.GetEntityTypes()
                .FirstOrDefault(et => string.Equals(et.GetTableName(), tableName, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>Quotes a Postgres identifier; the only untrusted part of built SQL — values always go through parameters.</summary>
        private static string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

        private static List<ColumnInfo> GetColumnInfo(IEntityType entityType)
        {
            var tableName = entityType.GetTableName()!;
            var storeObject = Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Table(tableName, entityType.GetSchema());
            var pkProps = entityType.FindPrimaryKey()?.Properties ?? (IReadOnlyList<IProperty>)Array.Empty<IProperty>();

            var columns = new List<ColumnInfo>();
            foreach (var prop in entityType.GetProperties())
            {
                var columnName = prop.GetColumnName(storeObject);
                if (columnName == null) continue;

                var clrType = Nullable.GetUnderlyingType(prop.ClrType) ?? prop.ClrType;
                Dictionary<int, string>? enumLabels = null;
                if (clrType.IsEnum)
                {
                    enumLabels = Enum.GetValues(clrType).Cast<object>()
                        .ToDictionary(v => Convert.ToInt32(v), v => v.ToString()!);
                }

                columns.Add(new ColumnInfo
                {
                    Name = columnName,
                    StoreType = prop.GetColumnType(),
                    ClrType = clrType,
                    IsPrimaryKey = pkProps.Contains(prop),
                    IsNullable = prop.IsNullable,
                    IsAutoGenerated = prop.ValueGenerated == ValueGenerated.OnAdd && pkProps.Contains(prop),
                    EnumLabels = enumLabels
                });
            }
            return columns;
        }
    }
}
