using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Auto_Wash.Data;
using Auto_Wash.Data.Entities;
using Auto_Wash.Helpers;

namespace Auto_Wash.Controllers
{
    /// <summary>
    /// Demo-only tools: browse and edit raw database tables from the admin UI
    /// so demo scenarios (booking times, statuses...) can be tweaked without
    /// opening Supabase directly.
    /// </summary>
    public class DemoToolsController : Controller
    {
        private readonly AutoWashDbContext _context;
        private readonly FileLogger _auditLogger;

        public DemoToolsController(AutoWashDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _auditLogger = new FileLogger(System.IO.Path.Combine(env.ContentRootPath, "demo_tools_log.txt"));
        }

        /// <summary>Writes every demo-tools write operation to demo_tools_log.txt so demo edits stay traceable.</summary>
        private void Audit(string action, string details)
        {
            var user = HttpContext.Session.GetString("UserEmail")
                       ?? HttpContext.Session.GetString("UserRole")
                       ?? "unknown";
            _auditLogger.Log(Microsoft.Extensions.Logging.LogLevel.Information, 0,
                $"[{action}] by={user} {details}", null, (state, _) => state);
        }

        private bool IsAdminOrStaff()
        {
            var role = HttpContext.Session.GetString("UserRole");
            return string.Equals(role, "admin", StringComparison.OrdinalIgnoreCase) ||
                   string.Equals(role, "staff", StringComparison.OrdinalIgnoreCase);
        }

        [HttpGet]
        [Route("api/admin/demo-tools/tables")]
        public IActionResult GetTables()
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            try
            {
                var tables = _context.Model.GetEntityTypes()
                    .Where(et => et.GetTableName() != null)
                    .Select(et => new
                    {
                        name = et.GetTableName(),
                        columns = GetColumnInfo(et).Select(c => new
                        {
                            name = c.Name,
                            storeType = c.StoreType,
                            clrType = c.ClrType.Name,
                            isPrimaryKey = c.IsPrimaryKey,
                            isNullable = c.IsNullable,
                            isAutoGenerated = c.IsAutoGenerated,
                            enumLabels = c.EnumLabels
                        })
                    })
                    .OrderBy(t => t.name)
                    .ToList();

                return Ok(new { success = true, tables });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpGet]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> GetRows(string table, int page = 1, int pageSize = 20, string? search = null, string? sortBy = null, string? sortDir = null)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });

            if (page < 1) page = 1;
            if (pageSize < 1 || pageSize > 200) pageSize = 20;

            try
            {
                var tableName = entityType.GetTableName()!;
                var columns = GetColumnInfo(entityType);
                var pkColumns = columns.Where(c => c.IsPrimaryKey).Select(c => c.Name).ToList();
                // Sort column must exist in the EF model — rejects arbitrary identifiers
                var orderBy = pkColumns.Count > 0
                    ? string.Join(", ", pkColumns.Select(Quote))
                    : Quote(columns[0].Name);
                if (!string.IsNullOrWhiteSpace(sortBy))
                {
                    var sortColumn = columns.FirstOrDefault(c => string.Equals(c.Name, sortBy, StringComparison.OrdinalIgnoreCase));
                    if (sortColumn == null)
                    {
                        return BadRequest(new { success = false, message = $"Cột sort '{sortBy}' không tồn tại trong bảng '{table}'." });
                    }
                    var direction = string.Equals(sortDir, "desc", StringComparison.OrdinalIgnoreCase) ? "DESC" : "ASC";
                    orderBy = $"{Quote(sortColumn.Name)} {direction}";
                }

                // Search: match the term against every column, cast to text so it works for numbers/dates too
                var whereClause = "";
                if (!string.IsNullOrWhiteSpace(search))
                {
                    var likeConditions = columns.Select(c => $"{Quote(c.Name)}::text ILIKE @search");
                    whereClause = $" WHERE ({string.Join(" OR ", likeConditions)})";
                }

                var result = await WithConnectionAsync(async conn =>
                {
                    long totalCount;
                    using (var countCmd = conn.CreateCommand())
                    {
                        countCmd.CommandText = $"SELECT COUNT(*) FROM {Quote(tableName)}{whereClause}";
                        AddSearchParameter(countCmd, whereClause, search);
                        totalCount = Convert.ToInt64(await countCmd.ExecuteScalarAsync());
                    }

                    var rows = new List<Dictionary<string, object?>>();
                    using (var cmd = conn.CreateCommand())
                    {
                        cmd.CommandText =
                            $"SELECT * FROM {Quote(tableName)}{whereClause} ORDER BY {orderBy} " +
                            $"LIMIT {pageSize} OFFSET {(page - 1) * pageSize}";
                        AddSearchParameter(cmd, whereClause, search);
                        using var reader = await cmd.ExecuteReaderAsync();
                        while (await reader.ReadAsync())
                        {
                            var row = new Dictionary<string, object?>();
                            for (int i = 0; i < reader.FieldCount; i++)
                            {
                                row[reader.GetName(i)] = ReadValue(reader.GetValue(i));
                            }
                            rows.Add(row);
                        }
                    }

                    return new { totalCount, rows };
                });

                return Ok(new { success = true, page, pageSize, totalCount = result.totalCount, rows = result.rows });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        public class RowRequest
        {
            public Dictionary<string, JsonElement>? Pk { get; set; }
            public Dictionary<string, JsonElement>? Values { get; set; }
        }

        [HttpPut]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> UpdateRow(string table, [FromBody] RowRequest request)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });
            if (request?.Pk == null || request.Pk.Count == 0) return BadRequest(new { success = false, message = "Thiếu khóa chính (pk)." });
            if (request.Values == null || request.Values.Count == 0) return BadRequest(new { success = false, message = "Không có cột nào để cập nhật." });

            var columns = GetColumnInfo(entityType);

            try
            {
                var affected = await WithConnectionAsync(async conn =>
                {
                    using var cmd = conn.CreateCommand();
                    var setParts = new List<string>();
                    int i = 0;
                    foreach (var (colName, jsonValue) in request.Values)
                    {
                        var col = FindColumnOrThrow(columns, colName, table);
                        setParts.Add($"{Quote(col.Name)} = {AddTypedParameter(cmd, $"v{i++}", jsonValue, col)}");
                    }

                    var whereClause = BuildPkWhere(cmd, columns, request.Pk, table);
                    cmd.CommandText = $"UPDATE {Quote(entityType.GetTableName()!)} SET {string.Join(", ", setParts)} WHERE {whereClause}";
                    return await cmd.ExecuteNonQueryAsync();
                });

                if (affected == 0) return NotFound(new { success = false, message = "Không tìm thấy row với khóa chính này." });
                Audit($"UPDATE {table}", $"pk={JsonSerializer.Serialize(request.Pk)} values={JsonSerializer.Serialize(request.Values)}");
                return Ok(new { success = true, message = $"Đã cập nhật {affected} row.", affected });
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpPost]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> InsertRow(string table, [FromBody] RowRequest request)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });
            if (request?.Values == null || request.Values.Count == 0) return BadRequest(new { success = false, message = "Không có dữ liệu để thêm." });

            var columns = GetColumnInfo(entityType);

            try
            {
                var createdRow = await WithConnectionAsync(async conn =>
                {
                    using var cmd = conn.CreateCommand();
                    var colNames = new List<string>();
                    var placeholders = new List<string>();
                    int i = 0;
                    foreach (var (colName, jsonValue) in request.Values)
                    {
                        var col = FindColumnOrThrow(columns, colName, table);
                        if (col.IsAutoGenerated) continue; // identity PK — let the DB generate it
                        colNames.Add(Quote(col.Name));
                        placeholders.Add(AddTypedParameter(cmd, $"v{i++}", jsonValue, col));
                    }
                    if (colNames.Count == 0) throw new ArgumentException("Không có cột hợp lệ nào để thêm.");

                    cmd.CommandText =
                        $"INSERT INTO {Quote(entityType.GetTableName()!)} ({string.Join(", ", colNames)}) " +
                        $"VALUES ({string.Join(", ", placeholders)}) RETURNING *";

                    using var reader = await cmd.ExecuteReaderAsync();
                    if (!await reader.ReadAsync()) return null;
                    var row = new Dictionary<string, object?>();
                    for (int f = 0; f < reader.FieldCount; f++)
                    {
                        row[reader.GetName(f)] = ReadValue(reader.GetValue(f));
                    }
                    return row;
                });

                Audit($"INSERT {table}", $"values={JsonSerializer.Serialize(request.Values)}");
                return Ok(new { success = true, message = "Đã thêm row mới.", row = createdRow });
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpDelete]
        [Route("api/admin/demo-tools/tables/{table}/rows")]
        public async Task<IActionResult> DeleteRow(string table, [FromBody] RowRequest request)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            var entityType = FindEntityType(table);
            if (entityType == null) return NotFound(new { success = false, message = $"Không tìm thấy bảng '{table}'." });
            if (request?.Pk == null || request.Pk.Count == 0) return BadRequest(new { success = false, message = "Thiếu khóa chính (pk)." });

            var columns = GetColumnInfo(entityType);

            try
            {
                var affected = await WithConnectionAsync(async conn =>
                {
                    using var cmd = conn.CreateCommand();
                    var whereClause = BuildPkWhere(cmd, columns, request.Pk, table);
                    cmd.CommandText = $"DELETE FROM {Quote(entityType.GetTableName()!)} WHERE {whereClause}";
                    return await cmd.ExecuteNonQueryAsync();
                });

                if (affected == 0) return NotFound(new { success = false, message = "Không tìm thấy row với khóa chính này." });
                Audit($"DELETE {table}", $"pk={JsonSerializer.Serialize(request.Pk)}");
                return Ok(new { success = true, message = $"Đã xóa {affected} row.", affected });
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        /// <summary>
        /// Shifts every timestamp of a booking (and its queue rows) by N minutes so demo
        /// scenarios can be triggered instantly: shift ScheduledAt into the past to fire
        /// no-show, into the near future to fire reminders, or move Queue.CheckInAt back
        /// to jump wash stages. Shifting into the future re-arms the email flags.
        /// </summary>
        [HttpPost]
        [Route("api/admin/demo-tools/bookings/{id}/shift-time")]
        public async Task<IActionResult> ShiftBookingTime(int id, int minutes)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });
            if (minutes == 0) return BadRequest(new { success = false, message = "Số phút phải khác 0." });

            try
            {
                var booking = await _context.Bookings.FirstOrDefaultAsync(b => b.BookingId == id);
                if (booking == null) return NotFound(new { success = false, message = $"Không tìm thấy booking #{id}." });

                var shift = TimeSpan.FromMinutes(minutes);
                booking.ScheduledAt += shift;
                booking.CreatedAt += shift;
                if (booking.CheckInAt.HasValue) booking.CheckInAt += shift;
                if (booking.ConfirmedAt.HasValue) booking.ConfirmedAt += shift;
                if (booking.WashingAt.HasValue) booking.WashingAt += shift;
                if (booking.CompletedAt.HasValue) booking.CompletedAt += shift;
                if (booking.NoShowAt.HasValue) booking.NoShowAt += shift;
                if (booking.CancelledAt.HasValue) booking.CancelledAt += shift;
                if (booking.CheckedOutAt.HasValue) booking.CheckedOutAt += shift;

                bool flagsReset = false;
                if (booking.ScheduledAt > DateTime.Now)
                {
                    booking.Reminder1Sent = false;
                    booking.Reminder2Sent = false;
                    booking.NoShowEmailSent = false;
                    flagsReset = true;
                }

                var queues = await _context.Queues.Where(q => q.BookingId == id).ToListAsync();
                foreach (var q in queues)
                {
                    q.CheckInAt += shift;
                    if (q.StartedAt.HasValue) q.StartedAt += shift;
                    if (q.CompletedAt.HasValue) q.CompletedAt += shift;
                }

                // Update BookingTask rows for single source of truth workflow
                var tasks = await _context.BookingTasks
                    .Where(t => t.BookingId == id)
                    .OrderBy(t => t.SequenceOrder)
                    .ToListAsync();

                foreach (var task in tasks)
                {
                    if (task.StartedAt.HasValue) task.StartedAt += shift;
                    if (task.CompletedAt.HasValue) task.CompletedAt += shift;
                }

                if (minutes < 0)
                {
                    var activeTimedTask = tasks.FirstOrDefault(t => t.Status == BookingTaskStatus.InProgress && (t.TaskType == "CheckIn" || t.TaskType == "Washing" || t.TaskType == "AddonProcessing"));
                    if (activeTimedTask != null)
                    {
                        activeTimedTask.Status = BookingTaskStatus.Completed;
                        activeTimedTask.CompletedAt = DateTime.Now;

                        var nextPendingTask = tasks.FirstOrDefault(t => t.Status == BookingTaskStatus.Pending);
                        if (nextPendingTask != null)
                        {
                            nextPendingTask.Status = BookingTaskStatus.InProgress;
                            nextPendingTask.StartedAt = DateTime.Now;
                            foreach (var q in queues)
                            {
                                q.CurrentStage = nextPendingTask.TaskType;
                            }
                        }
                    }
                }

                await _context.SaveChangesAsync();

                Audit("SHIFT bookings", $"bookingId={id} minutes={minutes} queues={queues.Count} flagsReset={flagsReset}");
                return Ok(new
                {
                    success = true,
                    message = $"Đã dịch thời gian booking #{id} {(minutes > 0 ? "+" : "")}{minutes} phút" +
                              (flagsReset ? " (đã reset các cờ email nhắc lịch)." : "."),
                    scheduledAt = booking.ScheduledAt.ToString("yyyy-MM-ddTHH:mm:ss"),
                    queuesShifted = queues.Count,
                    flagsReset
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        /// <summary>
        /// Demo-only check-in: performs the same Queue-creation logic as the real
        /// check-in (AdminBookingService.CheckInBookingAsync) but skips the ±15min
        /// window and same-day checks — and never touches any *At column on the
        /// booking, so the customer's actual appointment schedule stays untouched.
        /// </summary>
        [HttpPost]
        [Route("api/admin/demo-tools/bookings/{id}/force-checkin")]
        public async Task<IActionResult> ForceCheckIn(int id)
        {
            if (!IsAdminOrStaff()) return Unauthorized(new { success = false, message = "Bạn không có quyền thực hiện hành động này!" });

            try
            {
                var booking = await _context.Bookings
                    .Include(b => b.Customer).ThenInclude(c => c.Account)
                    .Include(b => b.Customer).ThenInclude(c => c.Tier)
                    .Include(b => b.Vehicle)
                    .FirstOrDefaultAsync(b => b.BookingId == id);
                if (booking == null) return NotFound(new { success = false, message = $"Không tìm thấy đơn đặt lịch #{id}." });

                if (booking.Status == BookingStatus.NoShow || booking.Status == BookingStatus.Cancelled || booking.Status == BookingStatus.Completed)
                    return BadRequest(new { success = false, message = $"Không thể check-in lịch đặt đã {(booking.Status == BookingStatus.NoShow ? "quá hạn (No-Show)" : booking.Status == BookingStatus.Cancelled ? "bị hủy" : "hoàn thành")}." });

                if (booking.Status != BookingStatus.Confirmed)
                    return BadRequest(new { success = false, message = "Chỉ đơn đặt lịch đang ở trạng thái 'Đã xác nhận' mới có thể thực hiện check-in." });

                var strategy = _context.Database.CreateExecutionStrategy();
                return await strategy.ExecuteAsync(async () =>
                {
                    using var transaction = await _context.Database.BeginTransactionAsync();
                    try
                    {
                        await _context.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(2410);");

                        var existingQueue = await _context.Queues
                            .FirstOrDefaultAsync(q => q.BookingId == booking.BookingId && q.Status != QueueStatus.Cancelled);

                        int queueId;
                        string message;
                        if (existingQueue != null)
                        {
                            booking.Status = BookingStatus.CheckedIn;
                            await _context.SaveChangesAsync();
                            await transaction.CommitAsync();
                            queueId = existingQueue.QueueId;
                            message = "Đơn đặt lịch đã được check-in vào hàng đợi.";
                        }
                        else
                        {
                            var today = DateTime.Today;
                            var lastPos = await _context.Queues
                                .Where(q => q.CheckInAt.Date == today && q.Status != QueueStatus.Cancelled)
                                .Select(q => (int?)q.Position)
                                .MaxAsync() ?? 0;

                            var newQueue = new Queue
                            {
                                BookingId = booking.BookingId,
                                VehicleId = booking.VehicleId,
                                CustomerId = booking.CustomerId,
                                LicensePlate = booking.Vehicle?.LicensePlate?.ToUpper()?.Trim() ?? string.Empty,
                                CustomerName = booking.Customer?.Account?.FullName ?? "Khách vãng lai",
                                TierId = booking.Customer?.TierId ?? 1,
                                Status = QueueStatus.Waiting,
                                Position = lastPos + 1,
                                CheckInAt = DateTime.Now,
                                StaffNote = booking.Notes ?? string.Empty
                            };
                            booking.Status = BookingStatus.CheckedIn;
                            _context.Queues.Add(newQueue);
                            await _context.SaveChangesAsync();
                            await transaction.CommitAsync();
                            queueId = newQueue.QueueId;
                            message = "Check-in thành công! Xe đã được thêm vào hàng đợi.";
                        }

                        Audit("FORCE-CHECKIN bookings", $"bookingId={id} queueId={queueId} bypassedWindow=true");
                        return Ok(new { success = true, message, queueId });
                    }
                    catch (Exception)
                    {
                        await transaction.RollbackAsync();
                        throw;
                    }
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        private static ColumnInfo FindColumnOrThrow(List<ColumnInfo> columns, string name, string table)
        {
            return columns.FirstOrDefault(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase))
                ?? throw new ArgumentException($"Cột '{name}' không tồn tại trong bảng '{table}'.");
        }

        /// <summary>
        /// Adds a parameter carrying the JSON value as text and returns the SQL placeholder
        /// with a cast to the column's store type — values never get concatenated into SQL.
        /// </summary>
        private static string AddTypedParameter(DbCommand cmd, string name, JsonElement jsonValue, ColumnInfo col)
        {
            var p = cmd.CreateParameter();
            p.ParameterName = name;
            if (jsonValue.ValueKind == JsonValueKind.Null ||
                (jsonValue.ValueKind == JsonValueKind.String && jsonValue.GetString() == "" && col.IsNullable && col.ClrType != typeof(string)))
            {
                p.Value = DBNull.Value;
                cmd.Parameters.Add(p);
                return $"@{name}";
            }
            p.Value = jsonValue.ValueKind == JsonValueKind.String ? jsonValue.GetString()! : jsonValue.GetRawText();
            cmd.Parameters.Add(p);
            return $"@{name}::{col.StoreType}";
        }

        private static string BuildPkWhere(DbCommand cmd, List<ColumnInfo> columns, Dictionary<string, JsonElement> pk, string table)
        {
            var pkColumns = columns.Where(c => c.IsPrimaryKey).ToList();
            if (pkColumns.Count == 0) throw new ArgumentException($"Bảng '{table}' không có khóa chính — không hỗ trợ sửa/xóa.");

            var parts = new List<string>();
            int i = 0;
            foreach (var pkCol in pkColumns)
            {
                if (!pk.TryGetValue(pkCol.Name, out var value) &&
                    !pk.TryGetValue(pkCol.Name.ToLowerInvariant(), out value))
                {
                    throw new ArgumentException($"Thiếu giá trị khóa chính '{pkCol.Name}'.");
                }
                parts.Add($"{Quote(pkCol.Name)} = {AddTypedParameter(cmd, $"k{i++}", value, pkCol)}");
            }
            return string.Join(" AND ", parts);
        }

        private sealed class ColumnInfo
        {
            public string Name { get; init; } = string.Empty;
            public string StoreType { get; init; } = string.Empty;
            public Type ClrType { get; init; } = typeof(object);
            public bool IsPrimaryKey { get; init; }
            public bool IsNullable { get; init; }
            public bool IsAutoGenerated { get; init; }
            public Dictionary<int, string>? EnumLabels { get; init; }
        }

        private IEntityType? FindEntityType(string tableName)
        {
            return _context.Model.GetEntityTypes()
                .FirstOrDefault(et => string.Equals(et.GetTableName(), tableName, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>Quotes a Postgres identifier; the only untrusted part of built SQL — values always go through parameters.</summary>
        private static string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

        private async Task<T> WithConnectionAsync<T>(Func<DbConnection, Task<T>> action)
        {
            var conn = _context.Database.GetDbConnection();
            bool wasOpen = conn.State == System.Data.ConnectionState.Open;
            if (!wasOpen) await conn.OpenAsync();
            try
            {
                return await action(conn);
            }
            finally
            {
                if (!wasOpen) await conn.CloseAsync();
            }
        }

        [HttpGet]
        [Route("api/admin/demo-tools/audit-db")]
        public async Task<IActionResult> AuditDatabase()
        {
            try
            {
                var services = await _context.Services.AsNoTracking().OrderBy(s => s.ServiceId).ToListAsync();
                var tiers = await _context.Tiers.AsNoTracking().OrderBy(t => t.TierId).ToListAsync();
                var loyaltyConfig = await _context.LoyaltyConfigs.AsNoTracking().FirstOrDefaultAsync();
                var rewards = await _context.Rewards.AsNoTracking().OrderBy(r => r.RewardId).ToListAsync();
                var redemptionsCount = await _context.RewardRedemptions.CountAsync();
                var referencedRewardIds = await _context.RewardRedemptions
                    .AsNoTracking()
                    .Select(rr => rr.RewardId)
                    .Distinct()
                    .ToListAsync();

                return Ok(new
                {
                    success = true,
                    auditTime = DateTime.UtcNow,
                    loyaltyConfig = new
                    {
                        configId = loyaltyConfig?.ConfigId,
                        pointsPerThousandVND = loyaltyConfig?.PointsPerThousandVND
                    },
                    servicesCount = services.Count,
                    services = services.Select(s => new { s.ServiceId, s.ServiceName, s.BasePrice, isAddOn = s.Category == ServiceCategory.AddOn, s.IsActive }),
                    tiersCount = tiers.Count,
                    tiers = tiers.Select(t => new { t.TierId, t.TierName, t.MinRankingBalance, t.MaintainBalance, t.PointMultiplier, t.DiscountPercent }),
                    rewardsCount = rewards.Count,
                    referencedRewardIds,
                    totalRedemptionsCount = redemptionsCount,
                    rewards = rewards.Select(r => new
                    {
                        r.RewardId,
                        r.RewardName,
                        r.RewardType,
                        r.PointCost,
                        r.DiscountValue,
                        r.MinTierId,
                        r.ServiceId,
                        r.ValidDays,
                        r.IsActive,
                        r.IsAutomaticReward,
                        isReferencedInRedemptions = referencedRewardIds.Contains(r.RewardId)
                    })
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        [HttpPost]
        [Route("api/admin/demo-tools/sync-refactor-db")]
        public async Task<IActionResult> SyncRefactorDatabase()
        {
            try
            {
                // 1. Sync LoyaltyConfig (PointsPerThousandVND = 10)
                var config = await _context.LoyaltyConfigs.FirstOrDefaultAsync();
                if (config == null)
                {
                    config = new LoyaltyConfig
                    {
                        ConfigId = 1,
                        PointsPerThousandVND = 10,
                        PointExpiryMonths = 12,
                        TierReviewDayOfMonth = 1,
                        RankingWindowYears = 2,
                        UpdatedAt = DateTime.UtcNow
                    };
                    _context.LoyaltyConfigs.Add(config);
                }
                else
                {
                    config.PointsPerThousandVND = 10;
                    config.UpdatedAt = DateTime.UtcNow;
                }

                // 2. Sync Tiers
                var existingTiers = await _context.Tiers.ToListAsync();
                var tierDefs = new[]
                {
                    new Tier { TierId = 1, TierName = "Member", MinRankingBalance = 0, MaintainBalance = 0, PointMultiplier = 1.00m, DiscountPercent = 0.00m, QueuePriority = 1, BookingWindowDays = 7, SortOrder = 1 },
                    new Tier { TierId = 2, TierName = "Silver", MinRankingBalance = 50000, MaintainBalance = 30000, PointMultiplier = 1.25m, DiscountPercent = 2.00m, QueuePriority = 2, BookingWindowDays = 14, SortOrder = 2 },
                    new Tier { TierId = 3, TierName = "Gold", MinRankingBalance = 150000, MaintainBalance = 100000, PointMultiplier = 1.50m, DiscountPercent = 5.00m, QueuePriority = 3, BookingWindowDays = 30, SortOrder = 3 },
                    new Tier { TierId = 4, TierName = "Platinum", MinRankingBalance = 300000, MaintainBalance = 200000, PointMultiplier = 2.00m, DiscountPercent = 10.00m, QueuePriority = 4, BookingWindowDays = 60, SortOrder = 4 }
                };

                foreach (var td in tierDefs)
                {
                    var t = existingTiers.FirstOrDefault(x => x.TierId == td.TierId || x.TierName.Equals(td.TierName, StringComparison.OrdinalIgnoreCase));
                    if (t != null)
                    {
                        t.TierName = td.TierName;
                        t.MinRankingBalance = td.MinRankingBalance;
                        t.MaintainBalance = td.MaintainBalance;
                        t.PointMultiplier = td.PointMultiplier;
                        t.DiscountPercent = td.DiscountPercent;
                        t.QueuePriority = td.QueuePriority;
                        t.BookingWindowDays = td.BookingWindowDays;
                        t.SortOrder = td.SortOrder;
                    }
                    else
                    {
                        _context.Tiers.Add(td);
                    }
                }

                // 3. Sync Services (10x Demo scale)
                var existingServices = await _context.Services.ToListAsync();
                var serviceDefs = new[]
                {
                    new Service { ServiceId = 999, ServiceName = "Standard Car Wash", Description = "Dịch vụ rửa xe tiêu chuẩn bao gồm: Rửa ngoại thất, vệ sinh bánh xe, hút bụi nội thất, lau kính, lau taplo, dưỡng nội thất cơ bản, kiểm tra cuối.", Category = ServiceCategory.Basic, BasePrice = 14900, EstimatedMinutes = 50, IsActive = true, IsFeatured = true },
                    new Service { ServiceId = 1000, ServiceName = "Premium Car Wash", Description = "Bao gồm tất cả gói Standard, cộng thêm: Rửa bọt cao cấp, đánh bóng lốp, vệ sinh nội thất sâu, dưỡng da ghế, phục hồi nhựa nội thất, hoàn thiện cao cấp.", Category = ServiceCategory.Premium, BasePrice = 29900, EstimatedMinutes = 90, IsActive = true, IsFeatured = true },
                    new Service { ServiceId = 1001, ServiceName = "Wax Coating", Description = "Phủ lớp sáp bảo vệ bề mặt sơn, tạo độ bóng cao và chống bám bẩn.", Category = ServiceCategory.AddOn, BasePrice = 7900, EstimatedMinutes = 15, IsActive = true, IsFeatured = false },
                    new Service { ServiceId = 1002, ServiceName = "Nano Ceramic Spray", Description = "Phủ ceramic nano tạm thời, tăng khả năng chống nước và bảo vệ sơn xe.", Category = ServiceCategory.AddOn, BasePrice = 19900, EstimatedMinutes = 25, IsActive = true, IsFeatured = false },
                    new Service { ServiceId = 1003, ServiceName = "Engine Bay Cleaning", Description = "Vệ sinh khoang máy an toàn, loại bỏ bụi bẩn và dầu mỡ tích tụ.", Category = ServiceCategory.AddOn, BasePrice = 9900, EstimatedMinutes = 20, IsActive = true, IsFeatured = false },
                    new Service { ServiceId = 1004, ServiceName = "Interior Odor Removal", Description = "Khử mùi hôi nội thất và làm mới không khí cabin xe.", Category = ServiceCategory.AddOn, BasePrice = 6900, EstimatedMinutes = 15, IsActive = true, IsFeatured = false },
                    new Service { ServiceId = 1005, ServiceName = "Leather Seat Conditioning", Description = "Dưỡng ẩm và bảo vệ ghế da, giúp da mềm mại và kéo dài tuổi thọ.", Category = ServiceCategory.AddOn, BasePrice = 12900, EstimatedMinutes = 20, IsActive = true, IsFeatured = false },
                    new Service { ServiceId = 1006, ServiceName = "Headlight Restoration", Description = "Phục hồi đèn pha bị mờ, cải thiện khả năng chiếu sáng và thẩm mỹ.", Category = ServiceCategory.AddOn, BasePrice = 15900, EstimatedMinutes = 25, IsActive = true, IsFeatured = false }
                };

                foreach (var sd in serviceDefs)
                {
                    var s = existingServices.FirstOrDefault(x => x.ServiceId == sd.ServiceId);
                    if (s != null)
                    {
                        s.ServiceName = sd.ServiceName;
                        s.Description = sd.Description;
                        s.Category = sd.Category;
                        s.BasePrice = sd.BasePrice;
                        s.EstimatedMinutes = sd.EstimatedMinutes;
                        s.IsActive = sd.IsActive;
                        s.IsFeatured = sd.IsFeatured;
                    }
                    else
                    {
                        _context.Services.Add(sd);
                    }
                }

                // 4. Safe IN-PLACE Sync for Rewards (Preserving Primary Keys & Foreign Keys)
                var existingRewards = await _context.Rewards.ToListAsync();
                var referencedRewardIds = await _context.RewardRedemptions
                    .Select(rr => rr.RewardId)
                    .Distinct()
                    .ToListAsync();

                var newRewardDefs = new[]
                {
                    new Reward { RewardId = 1001, RewardName = "Voucher 1.000đ", Description = "Voucher giảm trực tiếp 1.000đ cho hóa đơn dịch vụ", PointCost = 500, RewardType = "DiscountMoney", DiscountValue = 1000, ValidDays = 30, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1002, RewardName = "Voucher 2.000đ", Description = "Voucher giảm trực tiếp 2.000đ cho hóa đơn dịch vụ", PointCost = 1000, RewardType = "DiscountMoney", DiscountValue = 2000, ValidDays = 30, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1003, RewardName = "Voucher 5.000đ", Description = "Voucher giảm trực tiếp 5.000đ cho hóa đơn dịch vụ", PointCost = 2500, RewardType = "DiscountMoney", DiscountValue = 5000, ValidDays = 30, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1004, RewardName = "Voucher 10.000đ", Description = "Voucher giảm trực tiếp 10.000đ cho hóa đơn dịch vụ", PointCost = 5000, RewardType = "DiscountMoney", DiscountValue = 10000, ValidDays = 30, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1005, RewardName = "Giảm giá 5%", Description = "Voucher giảm giá 5% (tối đa 5.000đ) cho hóa đơn dịch vụ", PointCost = 3500, RewardType = "DiscountPercent", DiscountValue = 5, ValidDays = 30, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1006, RewardName = "Giảm giá 10%", Description = "Voucher giảm giá 10% (tối đa 10.000đ) cho hóa đơn dịch vụ", PointCost = 7000, RewardType = "DiscountPercent", DiscountValue = 10, ValidDays = 30, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1007, RewardName = "Quà Nâng Hạng Silver (Voucher 5%)", Description = "Voucher giảm 5% (tối đa 5.000đ) mừng nâng hạng Silver", PointCost = 0, RewardType = "UpgradeReward", DiscountValue = 5, MinTierId = 2, ValidDays = 60, IsActive = true, IsAutomaticReward = true },
                    new Reward { RewardId = 1008, RewardName = "Quà Nâng Hạng Gold (Voucher 10% + Tire Shine)", Description = "Voucher giảm 10% (tối đa 10.000đ) + 01 lượt đánh bóng lốp mừng nâng hạng Gold", PointCost = 0, RewardType = "UpgradeReward", DiscountValue = 10, MinTierId = 3, ValidDays = 60, IsActive = true, IsAutomaticReward = true },
                    new Reward { RewardId = 1009, RewardName = "Quà Nâng Hạng Platinum (Voucher 15% + Standard Wash + Birthday Gift)", Description = "Voucher giảm 15% (tối đa 15.000đ) + 01 lượt rửa xe miễn phí + Quà sinh nhật độc quyền mừng nâng hạng Platinum", PointCost = 0, RewardType = "UpgradeReward", DiscountValue = 15, MinTierId = 4, ValidDays = 90, IsActive = true, IsAutomaticReward = true },
                    new Reward { RewardId = 1010, RewardName = "Mũ bảo hiểm AutoWash", Description = "Mũ bảo hiểm nửa đầu in logo AutoWash cao cấp", PointCost = 500, RewardType = "PhysicalGift", ValidDays = 60, StockLimit = 50, IsActive = true, IsAutomaticReward = false },
                    new Reward { RewardId = 1011, RewardName = "Rửa xe tiêu chuẩn miễn phí", Description = "Voucher miễn phí dịch vụ Rửa xe tiêu chuẩn (Standard Wash)", PointCost = 1000, RewardType = "Free_Wash", ServiceId = 999, ValidDays = 30, IsActive = true, IsAutomaticReward = false }
                };

                var targetIds = newRewardDefs.Select(r => r.RewardId).ToHashSet();

                // 4a. Update existing rewards by ID or Insert if missing
                foreach (var rd in newRewardDefs)
                {
                    var r = existingRewards.FirstOrDefault(x => x.RewardId == rd.RewardId);
                    if (r != null)
                    {
                        r.RewardName = rd.RewardName;
                        r.Description = rd.Description;
                        r.PointCost = rd.PointCost;
                        r.RewardType = rd.RewardType;
                        r.DiscountValue = rd.DiscountValue;
                        r.MinTierId = rd.MinTierId;
                        r.ServiceId = rd.ServiceId;
                        r.ValidDays = rd.ValidDays;
                        r.StockLimit = rd.StockLimit;
                        r.IsActive = rd.IsActive;
                        r.IsAutomaticReward = rd.IsAutomaticReward;
                    }
                    else
                    {
                        _context.Rewards.Add(rd);
                    }
                }

                // 4b. Deactivate or safely delete old obsolete rewards not in newRewardDefs
                foreach (var oldR in existingRewards.Where(x => !targetIds.Contains(x.RewardId)))
                {
                    if (referencedRewardIds.Contains(oldR.RewardId))
                    {
                        // FK Constraint protection: deactivate so it won't break historical redemptions
                        oldR.IsActive = false;
                    }
                    else
                    {
                        _context.Rewards.Remove(oldR);
                    }
                }

                await _context.SaveChangesAsync();

                return Ok(new { success = true, message = "Đã đồng bộ dữ liệu PostgreSQL thành công!" });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }

        private static void AddSearchParameter(DbCommand cmd, string whereClause, string? search)
        {
            if (string.IsNullOrEmpty(whereClause)) return;
            var p = cmd.CreateParameter();
            p.ParameterName = "search";
            p.Value = $"%{search}%";
            cmd.Parameters.Add(p);
        }

        /// <summary>Converts a raw DB value to a JSON-friendly shape; matches datetime-local format on the frontend.</summary>
        private static object? ReadValue(object? value)
        {
            if (value == null || value is DBNull) return null;
            if (value is DateTime dt) return dt.ToString("yyyy-MM-ddTHH:mm:ss");
            if (value is byte[] bytes) return $"[bytea {bytes.Length} bytes]";
            return value;
        }

        private static List<ColumnInfo> GetColumnInfo(IEntityType entityType)
        {
            var tableName = entityType.GetTableName()!;
            var storeObject = Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Table(tableName, entityType.GetSchema());
            var pkProps = entityType.FindPrimaryKey()?.Properties ?? (IReadOnlyList<IProperty>)Array.Empty<IProperty>();

            var columns = new List<ColumnInfo>();
            foreach (var prop in entityType.GetProperties())
            {
                var columnName = prop.GetColumnName(storeObject);
                if (columnName == null) continue;

                var clrType = Nullable.GetUnderlyingType(prop.ClrType) ?? prop.ClrType;
                Dictionary<int, string>? enumLabels = null;
                if (clrType.IsEnum)
                {
                    enumLabels = Enum.GetValues(clrType).Cast<object>()
                        .ToDictionary(v => Convert.ToInt32(v), v => v.ToString()!);
                }

                columns.Add(new ColumnInfo
                {
                    Name = columnName,
                    StoreType = prop.GetColumnType(),
                    ClrType = clrType,
                    IsPrimaryKey = pkProps.Contains(prop),
                    IsNullable = prop.IsNullable,
                    IsAutoGenerated = prop.ValueGenerated == ValueGenerated.OnAdd && pkProps.Contains(prop),
                    EnumLabels = enumLabels
                });
            }
            return columns;
        }
    }
}
