// <auto-generated />
using System;
using Auto_Wash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auto_Wash.Migrations
{
    [DbContext(typeof(AutoWashDbContext))]
    partial class AutoWashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auto_Wash.Data.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("googleid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("AccountId")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_googleid");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_phone");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer")
                        .HasColumnName("baseprice");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancelreason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelledat");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cancelledby");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checkinat");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checkedoutat");

                    b.Property<string>("CheckedOutBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("checkedoutby");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completedat");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmedat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("finalprice");

                    b.Property<int>("FixedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("fixeddurationminutes");

                    b.Property<DateTime?>("NoShowAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("noshowat");

                    b.Property<bool>("NoShowEmailSent")
                        .HasColumnType("boolean")
                        .HasColumnName("noshowemailsent");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PointMultiplierSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pointmultipliersnapshot");

                    b.Property<int>("PointsDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("pointsdiscount");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer")
                        .HasColumnName("pointsearned");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("integer")
                        .HasColumnName("pointsredeemed");

                    b.Property<int?>("PointsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("pointsused");

                    b.Property<int?>("PointsValueVND")
                        .HasColumnType("integer")
                        .HasColumnName("pointsvaluevnd");

                    b.Property<int>("PromoDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("promodiscount");

                    b.Property<int?>("RatingBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("ratingbonuspoints");

                    b.Property<string>("RatingTags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ratingtags");

                    b.Property<int?>("RedemptionId")
                        .HasColumnType("integer")
                        .HasColumnName("redemptionid");

                    b.Property<bool>("Reminder1Sent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder1sent");

                    b.Property<bool>("Reminder2Sent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder2sent");

                    b.Property<int>("RescheduleCount")
                        .HasColumnType("integer")
                        .HasColumnName("reschedulecount");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reviewtext");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduledat");

                    b.Property<byte?>("Stars")
                        .HasColumnType("smallint")
                        .HasColumnName("stars");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TierDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("tierdiscount");

                    b.Property<int?>("TierIdSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("tieridsnapshot");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicleid");

                    b.Property<bool>("WaitingCheckoutEmailSent")
                        .HasColumnType("boolean")
                        .HasColumnName("waitingcheckoutemailsent");

                    b.Property<DateTime?>("WashingAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("washingat");

                    b.HasKey("BookingId")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_bookings_customerid");

                    b.HasIndex("RedemptionId")
                        .HasDatabaseName("ix_bookings_redemptionid");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("idx_bookings_scheduledat");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_bookings_status");

                    b.HasIndex("TierIdSnapshot")
                        .HasDatabaseName("ix_bookings_tieridsnapshot");

                    b.HasIndex("VehicleId", "ScheduledAt")
                        .IsUnique()
                        .HasDatabaseName("uq_bookings_vehicle_scheduledat_active")
                        .HasFilter("status != 4 AND status != 5 AND status != 7");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.BookingAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("performedby");

                    b.HasKey("Id")
                        .HasName("pk_bookingauditlogs");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_bookingauditlogs_bookingid");

                    b.ToTable("bookingauditlogs", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.BookingRescheduleHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changedby");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("NewScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("newscheduledat");

                    b.Property<DateTime>("OldScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("oldscheduledat");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_bookingreschedulehistories");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_bookingreschedulehistories_bookingid");

                    b.ToTable("bookingreschedulehistories", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.BookingService", b =>
                {
                    b.Property<int>("BookingServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingserviceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingServiceId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<int>("PriceSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("pricesnapshot");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("serviceid");

                    b.HasKey("BookingServiceId")
                        .HasName("pk_bookingservices");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_bookingservices_serviceid");

                    b.HasIndex("BookingId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("uq_bookingservices");

                    b.ToTable("bookingservices", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("accountid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joinedat");

                    b.Property<DateTime?>("LastTierReviewAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lasttierreviewat");

                    b.Property<DateTime?>("LastVisitAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastvisitat");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("integer")
                        .HasColumnName("lifetimepoints");

                    b.Property<string>("MembershipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("membershipcode");

                    b.Property<int>("PointBalance")
                        .HasColumnType("integer")
                        .HasColumnName("pointbalance");

                    b.Property<int>("RankingBalance")
                        .HasColumnType("integer")
                        .HasColumnName("rankingbalance");

                    b.Property<int>("TierId")
                        .HasColumnType("integer")
                        .HasColumnName("tierid");

                    b.Property<int>("TotalSpend")
                        .HasColumnType("integer")
                        .HasColumnName("totalspend");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("integer")
                        .HasColumnName("totalvisits");

                    b.HasKey("CustomerId")
                        .HasName("pk_customers");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_customers_accountid");

                    b.HasIndex("MembershipCode")
                        .IsUnique()
                        .HasDatabaseName("uq_customers_membershipcode");

                    b.HasIndex("TierId")
                        .HasDatabaseName("ix_customers_tierid");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.LoyaltyConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .HasColumnType("integer")
                        .HasColumnName("configid");

                    b.Property<int>("PointExpiryMonths")
                        .HasColumnType("integer")
                        .HasColumnName("pointexpirymonths");

                    b.Property<int>("PointsPerThousandVND")
                        .HasColumnType("integer")
                        .HasColumnName("pointsperthousandvnd");

                    b.Property<int>("RankingWindowYears")
                        .HasColumnType("integer")
                        .HasColumnName("rankingwindowyears");

                    b.Property<int>("TierReviewDayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("tierreviewdayofmonth");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedby");

                    b.HasKey("ConfigId")
                        .HasName("pk_loyaltyconfig");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_loyaltyconfig_updatedby");

                    b.ToTable("loyaltyconfig", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.LoyaltyTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transactionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expirydate");

                    b.Property<int?>("FromTierId")
                        .HasColumnType("integer")
                        .HasColumnName("fromtierid");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean")
                        .HasColumnName("isexpired");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int?>("RedemptionId")
                        .HasColumnType("integer")
                        .HasColumnName("redemptionid");

                    b.Property<string>("SpendingWindow")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("spendingwindow");

                    b.Property<int?>("ToTierId")
                        .HasColumnType("integer")
                        .HasColumnName("totierid");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transactiontype");

                    b.HasKey("TransactionId")
                        .HasName("pk_loyaltytransactions");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_loyaltytransactions_bookingid");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_lt_customerid");

                    b.HasIndex("FromTierId")
                        .HasDatabaseName("ix_loyaltytransactions_fromtierid");

                    b.HasIndex("RedemptionId")
                        .HasDatabaseName("ix_loyaltytransactions_redemptionid");

                    b.HasIndex("ToTierId")
                        .HasDatabaseName("ix_loyaltytransactions_totierid");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("idx_lt_type");

                    b.HasIndex("ExpiryDate", "IsExpired")
                        .HasDatabaseName("idx_lt_expiry");

                    b.ToTable("loyaltytransactions", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_notifications_customerid");

                    b.HasIndex("CustomerId", "IsRead")
                        .HasDatabaseName("idx_notifications_isread");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.OtpVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("otpid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OtpId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiresat");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("isused");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platenumber");

                    b.Property<string>("Purpose")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.HasKey("OtpId")
                        .HasName("pk_otpverifications");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_otp_email");

                    b.HasIndex("PlateNumber")
                        .HasDatabaseName("idx_otp_platenumber");

                    b.ToTable("otpverifications", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paidat");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("responsecode");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transactionno");

                    b.Property<string>("TxnRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("txnref");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_bookingid");

                    b.HasIndex("TxnRef")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_txnref");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Queue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("queueid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QueueId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CheckInAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checkinat");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("currentstage");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customername");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("licenseplate");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("StaffNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("staffnote");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("startedat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int?>("TierId")
                        .HasColumnType("integer")
                        .HasColumnName("tierid");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicleid");

                    b.HasKey("QueueId")
                        .HasName("pk_queue");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_queue_bookingid");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_queue_customerid");

                    b.HasIndex("LicensePlate")
                        .HasDatabaseName("idx_queue_plate");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_queue_status");

                    b.HasIndex("TierId")
                        .HasDatabaseName("ix_queue_tierid");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_queue_vehicleid");

                    b.ToTable("queue", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("uq_reviews_bookingid");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reviews_customerid");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rewardid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RewardId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discountvalue");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int?>("MaxRedemptionsPerCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("maxredemptionspercustomer");

                    b.Property<int?>("MinTierId")
                        .HasColumnType("integer")
                        .HasColumnName("mintierid");

                    b.Property<int>("PointCost")
                        .HasColumnType("integer")
                        .HasColumnName("pointcost");

                    b.Property<int>("RedeemedCount")
                        .HasColumnType("integer")
                        .HasColumnName("redeemedcount");

                    b.Property<string>("RewardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rewardname");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rewardtype");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("serviceid");

                    b.Property<int?>("StockLimit")
                        .HasColumnType("integer")
                        .HasColumnName("stocklimit");

                    b.Property<int>("ValidDays")
                        .HasColumnType("integer")
                        .HasColumnName("validdays");

                    b.HasKey("RewardId")
                        .HasName("pk_rewards");

                    b.HasIndex("MinTierId")
                        .HasDatabaseName("ix_rewards_mintierid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_rewards_serviceid");

                    b.ToTable("rewards", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.RewardRedemption", b =>
                {
                    b.Property<int>("RedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("redemptionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RedemptionId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiresat");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("redeemedat");

                    b.Property<int>("RewardId")
                        .HasColumnType("integer")
                        .HasColumnName("rewardid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usedat");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vouchercode");

                    b.HasKey("RedemptionId")
                        .HasName("pk_rewardredemptions");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_rewardredemptions_bookingid");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_redemptions_customerid");

                    b.HasIndex("RewardId")
                        .HasDatabaseName("ix_rewardredemptions_rewardid");

                    b.HasIndex("VoucherCode")
                        .IsUnique()
                        .HasDatabaseName("uq_rewardredemptions_vouchercode");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("idx_redemptions_customer_status");

                    b.ToTable("rewardredemptions", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("serviceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer")
                        .HasColumnName("baseprice");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimatedminutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsAddOn")
                        .HasColumnType("boolean")
                        .HasColumnName("isaddon");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("isfeatured");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("servicename");

                    b.HasKey("ServiceId")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            ServiceId = 999,
                            BasePrice = 250000,
                            Category = 1,
                            Description = "Dịch vụ rửa xe tiêu chuẩn bao gồm: Rửa ngoại thất, vệ sinh bánh xe, hút bụi nội thất, lau kính, lau taplo, dưỡng nội thất cơ bản, kiểm tra cuối.",
                            EstimatedMinutes = 60,
                            IsActive = true,
                            IsAddOn = false,
                            IsFeatured = true,
                            ServiceName = "Standard Car Wash"
                        });
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Tier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tierid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TierId"));

                    b.Property<int?>("BadgeColor")
                        .HasColumnType("integer")
                        .HasColumnName("badgecolor");

                    b.Property<int>("BookingWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("bookingwindowdays");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discountpercent");

                    b.Property<int>("MaintainBalance")
                        .HasColumnType("integer")
                        .HasColumnName("maintainbalance");

                    b.Property<int>("MinRankingBalance")
                        .HasColumnType("integer")
                        .HasColumnName("minrankingbalance");

                    b.Property<decimal>("PointMultiplier")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("pointmultiplier");

                    b.Property<int>("QueuePriority")
                        .HasColumnType("integer")
                        .HasColumnName("queuepriority");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tiername");

                    b.HasKey("TierId")
                        .HasName("pk_tiers");

                    b.ToTable("tiers", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.TierPerk", b =>
                {
                    b.Property<int>("PerkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("perkid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerkId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PerkType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("perktype");

                    b.Property<decimal>("PerkValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("perkvalue");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("serviceid");

                    b.Property<int>("TierId")
                        .HasColumnType("integer")
                        .HasColumnName("tierid");

                    b.HasKey("PerkId")
                        .HasName("pk_tierperks");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_tierperks_serviceid");

                    b.HasIndex("TierId")
                        .HasDatabaseName("ix_tierperks_tierid");

                    b.ToTable("tierperks", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("licenseplate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registeredat");

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicleclass");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_vehicles_customerid");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("uq_vehicles_licenseplate");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Booking", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customers_customerid");

                    b.HasOne("Auto_Wash.Data.Entities.RewardRedemption", "AppliedRedemption")
                        .WithMany("AppliedBookings")
                        .HasForeignKey("RedemptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_rewardredemptions_redemptionid");

                    b.HasOne("Auto_Wash.Data.Entities.Tier", null)
                        .WithMany()
                        .HasForeignKey("TierIdSnapshot")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_tier_snapshot");

                    b.HasOne("Auto_Wash.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_vehicles_vehicleid");

                    b.Navigation("AppliedRedemption");

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.BookingAuditLog", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookingauditlogs_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.BookingRescheduleHistory", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookingreschedulehistories_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.BookingService", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookingservices_bookings_bookingid");

                    b.HasOne("Auto_Wash.Data.Entities.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookingservices_services_serviceid");

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Customer", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("Auto_Wash.Data.Entities.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_accounts_accountid");

                    b.HasOne("Auto_Wash.Data.Entities.Tier", "Tier")
                        .WithMany("Customers")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_tiers_tierid");

                    b.Navigation("Account");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.LoyaltyConfig", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Account", "UpdatedByAccount")
                        .WithMany("UpdatedLoyaltyConfigs")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_loyaltyconfig_accounts_updatedby");

                    b.Navigation("UpdatedByAccount");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.LoyaltyTransaction", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_loyaltytransactions_bookings_bookingid");

                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_loyaltytransactions_customers_customerid");

                    b.HasOne("Auto_Wash.Data.Entities.Tier", "FromTier")
                        .WithMany()
                        .HasForeignKey("FromTierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_loyaltytransactions_tiers_fromtierid");

                    b.HasOne("Auto_Wash.Data.Entities.RewardRedemption", "RewardRedemption")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("RedemptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_loyaltytransactions_rewardredemptions_redemptionid");

                    b.HasOne("Auto_Wash.Data.Entities.Tier", "ToTier")
                        .WithMany()
                        .HasForeignKey("ToTierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_loyaltytransactions_tiers_totierid");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("FromTier");

                    b.Navigation("RewardRedemption");

                    b.Navigation("ToTier");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Notification", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_customers_customerid");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Payment", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("Auto_Wash.Data.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_bookingid");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Queue", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithMany("Queues")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_bookings_bookingid");

                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany("Queues")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_customers_customerid");

                    b.HasOne("Auto_Wash.Data.Entities.Tier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_tiers_tierid");

                    b.HasOne("Auto_Wash.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Queues")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_vehicles_vehicleid");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Tier");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Review", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithOne()
                        .HasForeignKey("Auto_Wash.Data.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_bookingid");

                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_customers_customerid");

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Reward", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Tier", "MinTier")
                        .WithMany()
                        .HasForeignKey("MinTierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rewards_tiers_mintierid");

                    b.HasOne("Auto_Wash.Data.Entities.Service", "Service")
                        .WithMany("Rewards")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rewards_services_serviceid");

                    b.Navigation("MinTier");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.RewardRedemption", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Booking", "Booking")
                        .WithMany("RelatedRedemptions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rewardredemptions_bookings_bookingid");

                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rewardredemptions_customers_customerid");

                    b.HasOne("Auto_Wash.Data.Entities.Reward", "Reward")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rewardredemptions_rewards_rewardid");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.TierPerk", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Service", "Service")
                        .WithMany("TierPerks")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tierperks_services_serviceid");

                    b.HasOne("Auto_Wash.Data.Entities.Tier", "Tier")
                        .WithMany("TierPerks")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tierperks_tiers_tierid");

                    b.Navigation("Service");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("Auto_Wash.Data.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_customers_customerid");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Account", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("UpdatedLoyaltyConfigs");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Booking", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Payment");

                    b.Navigation("Queues");

                    b.Navigation("RelatedRedemptions");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LoyaltyTransactions");

                    b.Navigation("Notifications");

                    b.Navigation("Queues");

                    b.Navigation("RewardRedemptions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Reward", b =>
                {
                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.RewardRedemption", b =>
                {
                    b.Navigation("AppliedBookings");

                    b.Navigation("LoyaltyTransactions");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Service", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("Rewards");

                    b.Navigation("TierPerks");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Tier", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("TierPerks");
                });

            modelBuilder.Entity("Auto_Wash.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Queues");
                });
#pragma warning restore 612, 618
        }
    }
}
